// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheatreOfTheMind.Data;

#nullable disable

namespace TheatreOfTheMind.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322105521_AddSpecialistsTable")]
    partial class AddSpecialistsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheatreOfTheMind.Models.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cha")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassAbilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Con")
                        .HasColumnType("integer");

                    b.Property<int>("Dex")
                        .HasColumnType("integer");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("Initiative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Int")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreparedSpells")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SavBreathAttack")
                        .HasColumnType("integer");

                    b.Property<int>("SavDeathPoison")
                        .HasColumnType("integer");

                    b.Property<int>("SavParalysisStone")
                        .HasColumnType("integer");

                    b.Property<int>("SavSpellsStaffRod")
                        .HasColumnType("integer");

                    b.Property<int>("SavWands")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Spellbook")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Str")
                        .HasColumnType("integer");

                    b.Property<int>("Thac0")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeaponMasteries")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Wis")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.ExpeditionState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisabledRaces")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ForemanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForemanTokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpeditionState");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Login", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Token");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Mercenary", b =>
                {
                    b.Property<Guid>("MercenaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MercenaryId");

                    b.HasIndex("Type", "Race")
                        .IsUnique();

                    b.ToTable("Mercenaries");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.PackAnimal", b =>
                {
                    b.Property<Guid>("PackAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedWagonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PackAnimalId");

                    b.HasIndex("AssignedWagonId");

                    b.ToTable("PackAnimals");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Specialist", b =>
                {
                    b.Property<Guid>("SpecialistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecialistId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Stash", b =>
                {
                    b.Property<Guid>("StashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Copper")
                        .HasColumnType("integer");

                    b.Property<int>("Electrum")
                        .HasColumnType("integer");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Platinum")
                        .HasColumnType("integer");

                    b.Property<bool>("Removable")
                        .HasColumnType("boolean");

                    b.Property<bool>("Shared")
                        .HasColumnType("boolean");

                    b.Property<int>("Silver")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("StashId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Shared");

                    b.ToTable("Stashes");

                    b.HasData(
                        new
                        {
                            StashId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Copper = 0,
                            Electrum = 0,
                            Equipment = "[]",
                            Gold = 0,
                            Name = "Expedition Caravan",
                            Platinum = 0,
                            Removable = false,
                            Shared = true,
                            Silver = 0,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.VttSceneEntity", b =>
                {
                    b.Property<string>("SceneId")
                        .HasColumnType("text");

                    b.Property<string>("Counters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GridColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GridH")
                        .HasColumnType("integer");

                    b.Property<double>("GridOffsetX")
                        .HasColumnType("double precision");

                    b.Property<double>("GridOffsetY")
                        .HasColumnType("double precision");

                    b.Property<double>("GridOpacity")
                        .HasColumnType("double precision");

                    b.Property<int>("GridThickness")
                        .HasColumnType("integer");

                    b.Property<int>("GridW")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SceneId");

                    b.ToTable("VttScenes");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Wagon", b =>
                {
                    b.Property<Guid>("WagonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WagonId");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Character", b =>
                {
                    b.HasOne("TheatreOfTheMind.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.PackAnimal", b =>
                {
                    b.HasOne("TheatreOfTheMind.Models.Wagon", "AssignedWagon")
                        .WithMany("AssignedAnimals")
                        .HasForeignKey("AssignedWagonId");

                    b.Navigation("AssignedWagon");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Stash", b =>
                {
                    b.HasOne("TheatreOfTheMind.Models.Character", "Character")
                        .WithMany("Stashes")
                        .HasForeignKey("CharacterId");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.User", b =>
                {
                    b.HasOne("TheatreOfTheMind.Models.Login", "Login")
                        .WithOne()
                        .HasForeignKey("TheatreOfTheMind.Models.User", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Character", b =>
                {
                    b.Navigation("Stashes");
                });

            modelBuilder.Entity("TheatreOfTheMind.Models.Wagon", b =>
                {
                    b.Navigation("AssignedAnimals");
                });
#pragma warning restore 612, 618
        }
    }
}
